### PR TITLE
Fix pr247 conflicts

### PR DESCRIPTION
**Pull request by vamsikalagaturu**

### CODE REVIEW

**Comment by JafarAbdi** [comment]
Thanks @vamsikalagaturu, do you mind discarding the unrelated commits?

**Comment by vamsikalagaturu** [comment]
but they are the latest commits in the upstream. i rebased to head and resolved conflicts. so, it should be fine for the PR I think right?

**Comment by JafarAbdi** [comment]
They aren't related to our changes, so they will mess up the PR

**Comment by vamsikalagaturu** [comment]
can you try/verify? because "moveit_active" commit from the upstream caused the merge conflict that was mentioned in your PR. Or if its easier for you, you can directly rebase your original PR and discard this one.

**Pull request merged**
